### ISSUE TITLE
Is the project abandoned? 

### ISSUE THREAD

**Issue by konstantinosftw** [afuh/instagram#2]
Hello afuh, you've done great job!  I want to ask if you have abandoned the project or are you planning on implementing the rest of the functionalities in the list?

**Comment by afuh** [comment]
Hey @konstantinosftw, 
sorry for the delay, I just noticed the issue. 
It's not abandoned, but to be honest it isn't actively maintained. After all, the purpose of doing this was to practice, it was a huge exercise.
